language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/apache-solr-3.6.2
    - $TRAVIS_BUILD_DIR/apache-solr-3.6.2.tgz

php:
  - 5.5

matrix:
  include:
    - php: 5.6
      env: WP_TRAVISCI=phpcs


script:
  - echo 'hello world'

after_script:
  - |
    if [ -z "$CLU_RUN" ] || [ "master" != "$TRAVIS_BRANCH"] ; then
      echo "composer.lock update disabled for this build"
      return
    fi
    export PATH="$HOME/.composer/vendor/bin:$PATH"
    composer global require danielbachhuber/composer-lock-updater
    clu $CLU_REPO_URL
