language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install --prefer-source
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/install-solr.sh

script: phpunit
