name: Lint and Test
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/build-tools-ci:8.x-php7.4
    name: Lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/vendor
        key: test-lint-dependencies-{{ checksum "composer.json" }}
        restore-keys: test-lint-dependencies-{{ checksum "composer.json" }}

    - name: Install dependencies
      run: composer install -n --prefer-dist

    - name: Run PHP Lint
      run: composer phpcs

  test-behat:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/build-tools-ci:6.x
    name: Behat tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/vendor
        key: test-behat-dependencies-{{ checksum "composer.json" }}
        restore-keys: test-behat-dependencies-{{ checksum "composer.json" }}

    - name: Temp admin password
      run: echo $(openssl rand -hex 8) > /tmp/WORDPRESS_ADMIN_PASSWORD

    - name: Setup $BASH_ENV
      run: |
        echo 'export TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export TERMINUS_SITE=solr-power' >> $BASH_ENV
        echo 'export SITE_ENV=solr-power.ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_USERNAME=pantheon' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_EMAIL=no-reply@getpantheon.com' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_PASSWORD=$(cat /tmp/WORDPRESS_ADMIN_PASSWORD)' >> $BASH_ENV
        source $BASH_ENV

    - name: SSH Config
      run: echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"

    - name: Check for $GITHUB_TOKEN
      run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        echo "Setting GitHub OAuth token with suppressed ouput"
        {
          composer config -g github-oauth.github.com $GITHUB_TOKEN
        } &> /dev/null

    - name: Check for $TERMINUS_TOKEN
      run: |
        if [ -z "$TERMINUS_TOKEN" ]; then
          echo "TERMINUS_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        terminus auth:login --machine-token=$TERMINUS_TOKEN

    - name: Prepare for Behat tests  
      run: ./bin/behat-prepare.sh

    - name: Execute Behat tests
      run: ./bin/behat-test.sh --strict

    - name: Clean up Behat tests
      run: ./bin/behat-cleanup.sh