name: Lint and Test
on: [push]

jobs:
  lint:
    name: Begin Lint job
    uses: docker://quay.io/pantheon-public/build-tools-ci:8.x-php7.4

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/vendor
        key: test-lint-dependencies-{{ checksum "composer.json" }}
        restore-keys: test-lint-dependencies-{{ checksum "composer.json" }}

    - name: Install dependencies
      run: composer install -n --prefer-dist

    - name: Run PHP Lint
      run: composer phpcs

  test-behat:
    name: Begin Behat job
    uses: docker://quay.io/pantheon-public/build-tools-ci:6.x

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/vendor
        key: test-behat-dependencies-{{ checksum "composer.json" }}
        restore-keys: test-behat-dependencies-{{ checksum "composer.json" }}

    - name: Temp admin password
      run: echo $(openssl rand -hex 8) > /tmp/WORDPRESS_ADMIN_PASSWORD

    - name: Setup $BASH_ENV
      run: |
        echo 'export TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export TERMINUS_SITE=solr-power' >> $BASH_ENV
        echo 'export SITE_ENV=solr-power.ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_USERNAME=pantheon' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_EMAIL=no-reply@getpantheon.com' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_PASSWORD=$(cat /tmp/WORDPRESS_ADMIN_PASSWORD)' >> $BASH_ENV
        source $BASH_ENV

    - name: SSH Config
      run: echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"

    - name: Check for $GITHUB_TOKEN
      run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        echo "Setting GitHub OAuth token with suppressed ouput"
        {
          composer config -g github-oauth.github.com $GITHUB_TOKEN
        } &> /dev/null

    - name: Check for $TERMINUS_TOKEN
      run: |
        if [ -z "$TERMINUS_TOKEN" ]; then
          echo "TERMINUS_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        terminus auth:login --machine-token=$TERMINUS_TOKEN

    - name: Prepare for Behat tests  
      run: ./bin/behat-prepare.sh

    - name: Execute Behat tests
      run: ./bin/behat-test.sh --strict

    - name: Clean up Behat tests
      run: ./bin/behat-cleanup.sh

  test-phpunit:
    container: danielbachhuber/solr-wp:0.1.0
    services:
      mariadb:
        image: mariadb:10.3
    env:
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
      WP_CORE_DIR: /tmp/wordpress/

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/vendor
        key: test-phpunit-dependencies-{{ checksum "composer.json" }}
        restore-keys: test-phpunit-dependencies-{{ checksum "composer.json" }}
  
    - name: "Add PUBKEYs"
    run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B

    - name: "Install Extras" 
    run: |
      sudo apt-get update
      sudo apt-get install subversion
      sudo apt-get install -y libmagickwand-dev --no-install-recommends
      yes '' | sudo pecl install imagick || true
      sudo docker-php-ext-enable imagick
      sudo docker-php-ext-install mysqli
      sudo apt-get install mariadb-client-10.5
    
    - name: "Run Tests"
    run: |
      bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
      composer phpunit
      rm -rf $WP_TESTS_DIR $WP_CORE_DIR
      bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 nightly true
      WP_MULTISITE=1 composer phpunit